apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: url-shortener-dev
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/khaledelhannat/url-shortener-infra.git
    targetRevision: main
    path: environments/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: url-shortener-api

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
